### ISSUE TITLE
add other coin 

### ISSUE THREAD

**Issue by geeks121** [Pycomet/escrow-service-bot#1]
Can you add other coin support?
example dogecoin, xrp, xlm. and set escrow fee for us .

thanks for this great project

**Comment by Pycomet** [comment]
Yes, I would love to.

**Can you list out cryptocurrencies you advise I add to this project?** The important thing is that people are willing to trade with it as there would be no use if they are not willing to

Thank you for using my project.

**Comment by geeks121** [comment]
i advise to add xlm, xrp, and doge ,, why?
because very cheap for transaction fee ,, and people would love it because you add it ,,

**Comment by Pycomet** [comment]
I will work on this as the next version of this escrow service bot. Thank you for pitching the idea to me and I look forward to seeing your response to my updates.
