### ISSUE TITLE
AsyncTeleBot class does not exist

### ISSUE THREAD

**Issue by officialbishowb** [Pycomet/escrow-service-bot#1]
So after trying to start the bot, I saw an error message saying that telebot does not have an AsyncTeleBot class. After further investigation, I found that it should be telebot.TeleBot instead of telebot.AsyncTeleBot.

Please also use pipreqs to get the requirements.txt, as the file you provided does not contain all the required libraries.

**Comment by Pycomet** [comment]
Yes, this has been resolved, and reverted to using telebot.TeleBot
