### ISSUE TITLE
Add memo in transfer

### ISSUE THREAD

**Issue by geeks121** [Pycomet/escrow-service-bot#12]
add memo to transfer coin 

in xrp or xlm if user wish withdraw to an exhcange

**Comment by Pycomet** [comment]
Your receiving party for withdrawal is exclusively defined by you alone. What are you proposing?

**Comment by geeks121** [comment]
i suppose just to add memo after wallet address because some wallet or exchange ,, obey to use memo..
if no memo ,, the balance will not receive to personal address ..

**Comment by Pycomet** [comment]
What kind of wallet would mandatorily use a memo? All the valid transaction coins just need your block address, that's it
