### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by xcjantv** [Pycomet/escrow-service-bot#20]
Hi, can you please add the option for the bot owner to set a percentage of the transaction amount to be the fee, wich stays in the coinbase account?

This would be amazing!

**Comment by Pycomet** [comment]
Yes, that is an amazing idea, thanks. But how about when the bot is handling the smaller transactions. The percentage fee would certainly give a third party the ability to over charge a client

**Comment by xcjantv** [comment]
I dont think so. When there is a smaller transaction amount, the transaction fee would of course also very low...

**Comment by Pycomet** [comment]
You know this depends highly on the traffic at the time. Fees are not constant, they fluctuate a lot based on the market state
