### ISSUE TITLE
can't lauch main.py

### ISSUE THREAD

**Issue by xcjantv** [Pycomet/escrow-service-bot#21]
Hi, I finally got the main.py to launch. But when I press on start in telegram, nothing happens. What is the problem?

>  * Serving Flask app "main" (lazy loading)
>  * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: off
>  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

Help me please :)

**Comment by Pycomet** [comment]
First of all, you need to open `http://0.0.0.0:5000` on your browser to activate it through the webhook or you go in config and change DEBUG to True then it would just poll from your terminal

**Comment by xcjantv** [comment]
Hi, thanks for your reply. 
I dont have a gui. Just a shell.
Wich config do you mean? config.py?

**Comment by Pycomet** [comment]
Yes, I just made a new commit which includes a feature to let you switch between running locally and in production mood.

What you do is;

To run locally,
- Goto `config.py`
- Set `DEBUG=True`
- Run the app `python main.py`

And if you wish to deploy,
- Goto `config.py`
- Set `DEBUG=False`
- Run the app `python main.py`

**Comment by xcjantv** [comment]
I added this statement in config.py:

> from coinbase.wallet.client import Client
> from dotenv import load_dotenv
> load_dotenv()
> 
> # Configuration variable
> TOKEN = os.getenv("TOKEN")
> 
> ADMIN_ID = os.getenv("ADMIN_ID")
> 
> # Coinbase API for payments
> API_KEY = os.getenv("API_KEY")
> API_SECRET = os.getenv("API_SECRET")
> 
> bot = telebot.AsyncTeleBot(TOKEN, threaded=True)
> 
> import importdir
> importdir.do("handlers", globals())
> DEBUG=False

It didnt changed anything...

**Comment by xcjantv** [comment]
when I access 0.0.0.0:5000 it says escrow bot active, but the tlegram bot doesnt react to /start
