### ISSUE TITLE
Issue with db

### ISSUE THREAD

**Issue by xcjantv** [Pycomet/escrow-service-bot#22]
> >Traceback (most recent call last):
>   File "main.py", line 32, in <module>
>     bot.polling(none_stop=True)
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/telebot/__init__.py", line 392, in polling
>     self.__threaded_polling(none_stop, interval, timeout)
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/telebot/__init__.py", line 416, in __threaded_polling
>     self.worker_pool.raise_exceptions()
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/telebot/util.py", line 109, in raise_exceptions
>     six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/six.py", line 703, in reraise
>     raise value
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/telebot/util.py", line 60, in run
>     task(*args, **kwargs)
>   File "handlers/callbacks.py", line 26, in callback_answer
>     start_affiliate(call)
>   File "handlers/affiliate.py", line 9, in start_affiliate
>     user = get_user(msg=user)
>   File "/root/escrow-service-bot/functions.py", line 24, in get_user
>     user = session.query(User).filter_by(id=id).first()
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3300, in first
>     ret = list(self[0:1])
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3078, in __getitem__
>     return list(res)
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3405, in __iter__
>     return self._execute_and_instances(context)
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3430, in _execute_and_instances
>     result = conn.execute(querycontext.statement, self._params)
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
>     return meth(self, multiparams, params)
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
>     distilled_params,
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
>     e, statement, parameters, cursor, context
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
>     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
>     raise exception
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
>     cursor, statement, parameters, context
>   File "/root/escrow-service-bot/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "users" does not exist
> LINE 2: FROM users
>              ^
> 
> [SQL: SELECT users.id AS users_id, users.chat AS users_chat
> FROM users
> WHERE users.id = %(id_1)s
>  LIMIT %(param_1)s]
> [parameters: {'id_1': 1429075237, 'param_1': 1}]
> (Background on this error at: http://sqlalche.me/e/f405)
> 

Help me pls :)

**Comment by Pycomet** [comment]
This is as a result of your database not being linked up correctly to your bot application. The script works with a Postgresql database through the acces url

**Comment by Ola-Daniel** [comment]
This issue is the nonexistence of a table in the database and not the absence of the url for the database url. sqlalchemy does not automatically create a table , you should uncomment the create_all line in the model.py file to solve your error
