### ISSUE TITLE
Bugs : branch telescrow

### ISSUE THREAD

**Issue by geeks121** [Pycomet/escrow-service-bot#26]
- can't delete escrow id (trade) : You are not authorized to take this action. Please contact support! (i'm the admin)

- bot in group not show any next step after choosing seller and buyer.. (silent)

-  add bot to group show this :

🤖 Awaiting authorization from support. Contact @Telescrowbotsupport to pass screening process

**Comment by Pycomet** [comment]
You are not authorized to use this branch. This is a custom-built version.

Regardless of that, adding to the group need approval

**Comment by geeks121** [comment]
- how to to authorized to use branch?

- i don't understand .. since i set it as admin

**Comment by Pycomet** [comment]
Yes, I can add the dashboard, already made provision for its data on the bot. I basically just need to build the UI part
